### ISSUE TITLE
Arm behavior

### ISSUE THREAD

**Issue by Lamatrak** [kvoeten/UnrealBodyPlugin#2]
Hello, do you think we can find a solution for a better behavior of the arms? If I put one of my arms in the opposite direction, it will cross my body and have a bad bend.
Otherwise thank you for all your project is magic, continue like that you are brilliant! :)

**Comment by kvoeten** [comment]
Apologies for being unable to respond to this sooner, but I'm rather confused whether or not you have resolved your issue considering you closed the issue without leaving any report. If you haven't, I can think of various ways of improving the arm (and upper body in general) IK behavior.

**Comment by Lamatrak** [comment]
I redirected myself to the UBIK plugin for the upper part of the body because it is very successful that I have coupled with your IK Foot system.
It looks great.
Thank you for your reply
