### ISSUE TITLE
GPLv3 not compatible with unreal

### ISSUE THREAD

**Issue by muchcharles** [kvoeten/UnrealBodyPlugin#6]
"Product compliance
Ensure that your product complies with all applicable laws, regulations, and rules.  Verify your product doesn’t combine the Unreal Engine code with “Copyleft” open-source licenses. See the FAQ for more details."

https://www.unrealengine.com/en-US/release

**Comment by kvoeten** [comment]
License is indeed invalid and superseded by Epic's rules. I have never made an attempt to uphold copyright, but if I had attempted to do so those claims would have no legal foundation. Thank you for bringing this to my attention and the license has been updated to reflect this.
