### ISSUE TITLE
Vive_PawnCharacter grab cube and gun problem.

### ISSUE THREAD

**Issue by opengpu** [kvoeten/UnrealBodyPlugin#7]
Vive_PawnCharacter can grab cube, but after grab, move the hand BUT the cube's location is not right, eg. sometimes get away off the hand and the GrabSphere.
as for the GunBase in the VRExp example, can grab BUT the hands's never really reach the gun's surface...however, for the original VRExp example the hands can perfectly reach the gun's surface and grab at the gun's trigger.

i know you use the Hands' from the whole model's body instead of the seperated GraspingHand. BUT still not found where you did this. SO still not find how to fix the above grab problems...

**Comment by kvoeten** [comment]
Not reaching the surface/ trigger has to do with the collision method, unless you make changes to the AnimBP/ Trace method it doesn't support snapping to positions that may actively collide currently. This is also unplanned to fix. 

For the other described issues there's not enough information for me to reproduce the issue.
