### ISSUE TITLE
about the Body physics, is it able to open some physics inorder to avoid different parts of body overlap or even cross in each other.

### ISSUE THREAD

**Issue by opengpu** [kvoeten/UnrealBodyPlugin#8]
about the Body physics, is it able to open some physics inorder to avoid different parts of body overlap or even cross in each other.
eg. while waving the hands, the upperArm will often cross the Chest(spine_02)

**Comment by kvoeten** [comment]
In order to avoid the arms clipping with themselves RB anim methods can be utilized, for interaction with the world however there isn't a great system to do this with. Physics handles could enable it to a degree but they won't solve every bit of interaction.
